<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Submit_Positive</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>66d8a644-119a-48be-9650-d99301e2951c</testSuiteGuid>
   <testCaseLink>
      <guid>92a7b540-070b-4e60-bc59-f9746aa03242</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/TC_PF_001_SubmitSuccess_AllFieldInput</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d70abe2-ab24-460d-8d62-1e5f0c714ad2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b18b829-e317-43e9-aa8c-3ca0fde7c70d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a077ec81-a8ca-42e8-a507-e0f50e99fe44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae7770e5-9214-488a-95c6-c7918c02d426</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cbc78811-1f7a-4c29-88ed-1400e1038e28</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/TC_PF_004_SubmitSuccess_RequiredFieldInputValidation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb89629c-38a4-49cc-87b9-fe03beb518d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0f2a27f-1d0f-4eb2-834b-6ceb44e0a93c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7f6ace9-ba63-4ced-85df-85f293126f95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>365fae86-a188-4266-b3ee-0bb0ff221c9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5ffa11ec-12bc-47a9-ac10-ac8e17cd641d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/TC_PF_002_SubmitSuccess_MultipleHobies</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d82d0689-aaad-4faf-8d08-82ca308f3dd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107b98c8-7d98-45ab-94bc-7cc573956048</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a14dc75-3ba9-4ea8-9057-672abf5b699d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01304b13-3623-4758-ac6d-6f48038707a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddd03348-6318-4e45-b162-9e0ebf6d39bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positive Case/TC_PF_003_SubmitSuccess_MultipleSubject</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b9270cb-3ec1-4183-9117-00d576293fb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed192e28-9cfe-4f8c-b3a4-8472c900ed94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b6871ba-ac27-4cb6-906d-1c13cae0c086</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c04f93d7-3437-4ac5-b433-8f641e7127c2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
