<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Submit_Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>baae0df1-6426-4856-a7eb-e5c9a2d15be7</testSuiteGuid>
   <testCaseLink>
      <guid>da693b4c-85c9-45b9-ac01-a2b840227651</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_101_EmptyName</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c3c6eb-05d6-4898-b0d1-5432a45212e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>480a87ea-b784-40df-9041-d77466678c53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b78eb14-6e0f-4086-91e3-73fbfdebd135</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_102_EmptyPhoneNumber</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b755675f-8af9-434a-82e8-694e6f0d92bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d45e099-b67a-488c-a865-70781d4ea47c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc97a7e-b0a9-4e59-895d-bf5fa2cf6737</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6810f868-da9f-4d43-a818-29a208a6707f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_103_InvalidEmail</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8d11f3f-5195-4f76-9d40-a416d1d71e0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b840d6-42e2-400c-8898-2770d3f8b508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a715dfd1-8a07-46ce-81be-2ea7bd2684a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41b19f86-3e37-417c-ab91-721c837c3632</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49d15de2-bda3-4e1d-9ecf-f93bf51ca611</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_105_InvalidPhoneNumber</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b79e45a7-0402-4088-a9ce-9bcd44bac443</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d551fba-fdcc-4eb3-ba0c-488b7496964a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d8250b-e1d4-4fa2-a34b-513143d804d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f106c1b0-1e94-419a-837b-3265dbcca6d2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9448a4d-97c8-4c82-a1b6-cf442427428d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_104_InvalidNameFormat-BUG</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ada7cf8c-54b2-47d4-ad37-54d065ad4252</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a705b2cc-9a78-4cb6-bec8-c169690d3ab0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e144208b-001e-44c9-842d-960e3c32ad5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>222e1902-723b-420d-94fc-6a469645ba92</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f50b72e7-268f-4d01-9775-aa90fbe27d94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_106_NotChooseGender</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>716b3539-5695-4793-bc2c-17437025fcf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b398617-6bdc-4f5c-9744-39a2f498838d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c313763d-82f9-4ad7-97d1-1d33cf519561</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>881aee00-9cfb-424a-b090-20bfedc68698</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0eb9a3d-acd2-4976-aa04-dde8792d132d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negative Case/TC_PF_107_SystemAcceptsInvalidYear-BUG</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97c3c824-1a9f-4316-953b-0541b25580c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b369f76-6b50-4aa0-a1d5-a9b4eec2e729</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bb542b2-3bf3-45a1-9b5e-94e6e1c03be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4353a38-b3a2-4723-825a-2e10fda4ac0c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
